### ISSUE TITLE
2.7 introduces Unexpected Token error on our build

### ISSUE THREAD

**Issue by TheFrogPrince** [webpack/schema-utils#103]
- Operating System:  Azure 
- Node Version:  v6.11.2
- NPM Version:  v3.10.10
- webpack Version:  4.43.0
- schema-utils Version:  2.7

### Expected Behavior

Compile without errors.

### Actual Behavior

With the release of 2.7, our nightly builds started failing with:

ERROR in ./wwwroot/source/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
D:\_work\66\s\sites\MyBSWHealth2019\node_modules\schema-utils\dist\util\hints.js:16
  const currentSchema = { ...schema
                          ^^^

SyntaxError: Unexpected token ...

### Code

ERROR in ./wwwroot/source/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
D:\_work\66\s\sites\MyBSWHealth2019\node_modules\schema-utils\dist\util\hints.js:16
  const currentSchema = { ...schema
                          ^^^

SyntaxError: Unexpected token ...

### How Do We Reproduce?

I can't actually post our project, obviously.  Just letting ya'll know.

**Comment by TheFrogPrince** [comment]
Hard-coding the previous version in our package.json file solved the problem:

    "schema-utils": "2.6.6",

**Comment by evilebottnawi** [comment]
We doesn't support `node@6`, you can see it here https://github.com/webpack/schema-utils/blob/master/package.json#L17

**Comment by TheFrogPrince** [comment]
This

"schema-utils": "2.6.6",

could help other people like us who don't reference your project directly, but rather pick up the reference to your project from some other project.

**Comment by bobbylight** [comment]
Shouldn't a bump in required npm version be a major version bump, not a minor one, for reasons like this?  My project's build also failed due to our (company-mandated) use of node 6.9.2, with no code changes on our part, due to a transitive dependency from file-loader to schema-utils.

**Comment by TheFrogPrince** [comment]
No.  Their node requirement has actually been in there for a while.  The trouble is, the Engine has never been enforced by default.  I even tried to get it to be enforced on our build, and apparently have to upgrade a bunch of things to even get that to happen (which kinda defeats the point).  

Obviously... this is their first check-in using some of the newer features, so they've had a version marked as required that hasn't been required for a long time (until now).

One of the pitfalls of open-source (did you see how quickly my issue here got closed?).  :)

**Comment by evilebottnawi** [comment]
We **always** have `engines` https://github.com/webpack/schema-utils/blob/v2.0.0/package.json#L12, it is even in README, yarn fails with it, npm output warning, I don;t know why you ignore it and shame OSS and us

**Comment by bobbylight** [comment]
Thanks guys.

I don't think he was "shaming" you, just pointing out that your node version dependency was always set.

I appreciate you documenting this and sorry I didn't know of the hard dependency, but note that until my build broke today, I was unaware of schema-utils at all, since it's a transitive dependency, so I'm not familiar with its ins and outs.  Thanks for the clarification.

**Comment by zealo0724** [comment]
> Hard-coding the previous version in our package.json file solved the problem:
> 
> ```
> "schema-utils": "2.6.6",
> ```

you resolved my issue , thank you
