### ISSUE TITLE
can not build package with sass-loader and babel-loader

### ISSUE THREAD

**Issue by akeinhell** [webpack/schema-utils#104]
```
 /app/web/node_modules/sass-loader/node_modules/schema-utils/dist/util/hints.js:16
      const currentSchema = { ...schema
                              ^^^
    SyntaxError: Unexpected token ...

```
- Operating System: Ubuntu 20
- Node Version: 7.10
- NPM Version: 4.2.0
- webpack Version: 4.20.2
- schema-utils Version: sass-loader@8.0.0 requeries schema-utils"@^2.1.0

### Expected Behavior

can build old bundles with node 7.10

### Actual Behavior

Broken build in 2 loaders (sass-loader, babel-loader)

**Comment by evilebottnawi** [comment]
Update node to 8

**Comment by evilebottnawi** [comment]
Since 2 version we drop support node < 8, please read our CHANGELOG
