### ISSUE TITLE
Can't refer to ValidationError as a type in Typescript

### ISSUE THREAD

**Issue by sandersn** [webpack/schema-utils#114]
- Operating System: Linux
- Node Version: 12.18.3
- NPM Version: 6.14.6
- webpack Version: master
- schema-utils Version: 3.0.0

### Code

```ts
import { ValidationError } from 'schema-utils'
function f(v: ValidationError) {
  console.log(v.errors.length)
}
```

### Expected Behavior

No error in my editor (or when compiling with tsc).

### Actual Behavior

error on `v: ValidationError`: "ValidationError refers to a value, but is being used as a type here."

### How Do We Reproduce?

Paste above code into a file, `tsc --init`, `npm i schema-utils@3`.

Or open webpack's source to lib/util/registerExternalSerializer.js, it has the same problem. You might have to use `typescript@next` or `typescript@beta` to reproduce since I changed the way `require` type checks in Javascript recently.

### Probable Fix

index.d.ts should use the re-export syntax, not exports of import types. I'll put up a PR shortly.

**Comment by alexander-akait** [comment]
I think we can close it, feel free to feedback
