### ISSUE TITLE
Security Vulnerability in version 3.0.0

### ISSUE THREAD

**Issue by Skhoshhal** [webpack/schema-utils#131]
- Operating System: macOS
- Node Version: v14.15.1
- NPM Version: 7.18.1
- webpack Version:
- schema-utils Version: 3.0.0

### Actual Behavior
Whitesource found a High Severity Bug in vesroin 3.0.0, I am not sure where it is and what it is, it could be a license issue

<img width="1358" alt="Screen Shot 2021-06-18 at 16 09 59" src="https://user-images.githubusercontent.com/20300562/122574245-c15ca480-d04f-11eb-8762-80893aae8e36.png">

**Comment by alexander-akait** [comment]
Our license is MIT https://github.com/webpack/schema-utils/blob/master/package.json#L5

**Comment by alexander-akait** [comment]
I do not know what this report is and what it refers to
