### ISSUE TITLE
TypeError: Ajv is not a constructor

### ISSUE THREAD

**Issue by jonnytest1** [webpack/schema-utils#152]
### Bug report

we recently updated our angular poject to v13.x.x  now when i running `ng serve ` i get an error:

### Actual Behavior

```
[error] TypeError: Ajv is not a constructor
    at Object.<anonymous> (./node_modules/mini-css-extract-plugin/node_modules/schema-utils/dist/validate.js:66:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (./node_modules/mini-css-extract-plugin/node_modules/schema-utils/dist/index.js:6:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (./node_modules/mini-css-extract-plugin/dist/index.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
```

in the validate.js line 21 
it says require("ajv").default which is undefined - only require("ajv") returns the correct object

### Please paste the results of `npx webpack-cli info --aditional-package schema-utils` here, and mention other relevant information

PS:  ^-- there is a 'd' missing in the header

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 3.05 GB / 17.58 GB
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    npm: 8.3.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 95.0.1
  Packages:
    babel-loader: ^8.2.3 => 8.2.3 
    compression-webpack-plugin: ^8.0.1 => 8.0.1 
    ts-loader: ^9.2.6 => 9.2.6 
    webpack: ^5.65.0 => 5.65.0 
    worker-loader: ^3.0.8 => 3.0.8

**Comment by alexander-akait** [comment]
I think you have multiple `ajv` packages, there is bug in ajv side... Can you run `npm ls schema-utils` and `npm ls ajv`?

**Comment by jonnytest1** [comment]
npm ls schema-utils

├─┬ @angular-devkit/build-angular@13.1.2
│ ├─┬ copy-webpack-plugin@10.0.0
│ │ └── schema-utils@4.0.0
│ ├─┬ mini-css-extract-plugin@2.4.5
│ │ └── schema-utils@4.0.0
│ ├─┬ webpack-dev-middleware@5.2.2
│ │ └── schema-utils@4.0.0
│ └─┬ webpack-dev-server@4.6.0
│   └── schema-utils@4.0.0
├─┬ babel-loader@8.2.3
│ └── schema-utils@2.7.1
├─┬ compression-webpack-plugin@8.0.1
│ └── schema-utils@3.1.1
├─┬ webpack@5.65.0
│ ├── schema-utils@3.1.1
│ └─┬ terser-webpack-plugin@5.3.0
│   └── schema-utils@3.1.1
└─┬ worker-loader@3.0.8
  └── schema-utils@3.1.1
  
  
  ├─┬ @angular-devkit/build-angular@13.1.2
│ ├─┬ copy-webpack-plugin@10.0.0
│ │ └─┬ schema-utils@4.0.0
│ │   ├─┬ ajv-keywords@5.1.0
│ │   │ └── ajv@8.8.2 deduped
│ │   └── ajv@8.8.2
│ ├─┬ mini-css-extract-plugin@2.4.5
│ │ └─┬ schema-utils@4.0.0
│ │   └── ajv@6.12.6 deduped invalid: "^8.8.0" from node_modules/mini-css-extract-plugin/node_modules/schema-utils
│ ├─┬ webpack-dev-middleware@5.2.2
│ │ └─┬ schema-utils@4.0.0
│ │   ├─┬ ajv-keywords@5.1.0
│ │   │ └── ajv@8.8.2 deduped
│ │   └── ajv@8.8.2
│ └─┬ webpack-dev-server@4.6.0
│   └─┬ schema-utils@4.0.0
│     ├─┬ ajv-keywords@5.1.0
│     │ └── ajv@8.8.2 deduped
│     └── ajv@8.8.2
├─┬ @angular-devkit/core@13.1.2
│ ├─┬ ajv-formats@2.1.1
│ │ └── ajv@8.8.2
│ └── ajv@8.8.2
├─┬ ajv-merge-patch@4.1.0
│ └── ajv@6.12.6 deduped
├── ajv@6.12.6
├─┬ babel-loader@8.2.3
│ └─┬ schema-utils@2.7.1
│   ├─┬ ajv-keywords@3.5.2 invalid: "^5.0.0" from node_modules/mini-css-extract-plugin/node_modules/schema-utils
│   │ └── ajv@6.12.6 deduped invalid: "^8.8.0" from node_modules/mini-css-extract-plugin/node_modules/schema-utils
│   └── ajv@6.12.6 deduped
├─┬ compression-webpack-plugin@8.0.1
│ └─┬ schema-utils@3.1.1
│   └── ajv@6.12.6 deduped
├─┬ eslint@8.6.0
│ ├─┬ @eslint/eslintrc@1.0.5
│ │ └── ajv@6.12.6 deduped
│ └── ajv@6.12.6 deduped
├─┬ ng-packagr@13.1.2
│ └── ajv@8.8.2
├─┬ prettier-eslint@13.0.0
│ └─┬ eslint@7.32.0
│   ├─┬ @eslint/eslintrc@0.4.3
│   │ └── ajv@6.12.6 deduped invalid: "^8.8.0" from node_modules/mini-css-extract-plugin/node_modules/schema-utils
│   ├── ajv@6.12.6 deduped
│   └─┬ table@6.8.0
│     └── ajv@8.8.2
├─┬ webpack@5.65.0
│ ├─┬ schema-utils@3.1.1
│ │ └── ajv@6.12.6 deduped
│ └─┬ terser-webpack-plugin@5.3.0
│   └─┬ schema-utils@3.1.1
│     └── ajv@6.12.6 deduped invalid: "^8.8.0" from node_modules/mini-css-extract-plugin/node_modules/schema-utils
└─┬ worker-loader@3.0.8
  └─┬ schema-utils@3.1.1
    └── ajv@6.12.6 deduped

**Comment by alexander-akait** [comment]
Sounds like bug in npm, because old version should not be deduped, very weird...

**Comment by alexander-akait** [comment]
Can you try to remove `node_modules` and lock file and reinstall all deps again?

**Comment by jonnytest1** [comment]
oh 😅 thanks that worked

**Comment by jonnytest1** [comment]
unfortunately not a reproducable build :/ now i need to delete node_modules and lock file each time :/

**Comment by alexander-akait** [comment]
@jonnytest1 Can you report to npm?

**Comment by shye0000** [comment]
@jonnytest1 @alexander-akait 
Hi, I'm running into the same issue today, after installing a new package I start to have the exact same error

Here are my `npm ls ajv` output

before the new package installation: 
![image](https://user-images.githubusercontent.com/6414361/151286661-27392648-37ab-4c60-b53b-681dc320ca1a.png)

after the new package installation:
![image](https://user-images.githubusercontent.com/6414361/151286679-54b0f921-849e-4972-9fc3-ee655e39864e.png)

do you have a solution for that? or is there a npm issue that I can follow?

**Comment by alexander-akait** [comment]
Try to reinstall them using the latest version of npm

**Comment by shye0000** [comment]
@alexander-akait 
Indeed, after reinstall everything it works again. I had a trouble with a full re-installation, that's why I tried not to do it, but in the end I found a work around on that too, thx again.

**Comment by alexander-akait** [comment]
@shye0000 It is bug in `npm` :disappointed:

**Comment by shye0000** [comment]
@alexander-akait yeah, I think so too and I'd love to submit an issue to them, but I'm not sure how to explain this accurately.

**Comment by jonnytest1** [comment]
i figured out this bug came from using npm-force-resolution on i think glob-parent

**Comment by shye0000** [comment]
@jonnytest1 OMG, I also use `npm-force-resolution` to fix some package version to get rid of some annoying high vulnerability issues, I'll try "override" then

**Comment by jonnytest1** [comment]
also check wether that version is still the latest one of its package just in case
