### ISSUE TITLE
Provide better default error message on invalid properties

### ISSUE THREAD

**Issue by xz64** [webpack/schema-utils#35]
### Use Case

I am writing a webpack plugin and want to make sure users don't add extraneous properties to the options. The user should know what specific extraneous property caused the error. Currently it just says

`options should NOT have additional properties`

which does not help the user find out what exactly caused the error.

In the previous release of schema-utils (0.4.x) you would get a message like this which is more helpful:

`options['foo'] is an invalid additional property`

### Implementation

I believe this is caused by removing `errorDataPath: 'property'` from the ajv config as seen here: https://github.com/webpack-contrib/schema-utils/commit/1cbe4ef8bb67171fb8d3515fbbe620de064a188f#diff-813a48919ee26ea79873f7a8e049091fL19

- [ ] I'm open to work on this
  - [ ] I need help/mentorship
- [x] I'm unable to work on this

The `errorDataPath: 'property'` should be added back to the ajv config.

**Comment by michael-ciniawsky** [comment]
I will check if it could eventually be added back once I have a few minutes :)

**Comment by evilebottnawi** [comment]
Fixed in `2` version
