### ISSUE TITLE
support typescript loaders

### ISSUE THREAD

**Issue by vankop** [webpack/schema-utils#49]
- Operating System: any
- Node Version: any
- NPM Version: any
- webpack Version: @4
- schema-utils Version: latest

### Feature Proposal

I'm writing loader on TypeScript and it will be awesome if `schema-utils` will provide definitions respecting JSON schema specification (see [@types/json-schema](https://www.npmjs.com/package/@types/json-schema)) + ~~I did not found out (from small documentation on webpack.js.org) is it possible to increase DX (change error message, show possible options, i.e. developer made mistake in option name and I want provide suggestions)~~

### Feature Use Case

~~Increase DX,~~ TypeScript support

UPD: found out from code that webpack show suggestions depending on provided schema

**Comment by vankop** [comment]
@evilebottnawi ping

**Comment by evilebottnawi** [comment]
@vankop can you provide example?

**Comment by vankop** [comment]
example schema:
```javascript
import {JSONSchema4, JSONSchema6, JSONSchema7} from "json-schema";
import {ValidationError as AjvValidationError} from 'ajv';

interface ValidationErrorConfiguration {
  name: string,
  baseDataPath: string,
  postFormatter: (formattedError: string, error: AjvValidationError) => string;
}

interface ValidationError {}

declare var validate: {
  (schema: JSONSchema4 | JSONSchema6 | JSONSchema7, options: Array<object> | object, configuration: Partial<ValidationErrorConfiguration>): void;
  ValidationError: typeof ValidationError
}

export = validate;
```

**Comment by evilebottnawi** [comment]
@vankop why don't put this in https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by vankop** [comment]
I thought using `d.ts` files for libraries (especially for small libraries) is better. Since it easy to maintain, maybe TypeScript team will implement `d.ts` file generation from js files as well (so webpack  will be enable to autogenerate all his `d.ts`)

**Comment by evilebottnawi** [comment]
PR, welcome :+1:

**Comment by vankop** [comment]
i will check it locally with `npm link` and make PR later

**Comment by evilebottnawi** [comment]
@vankop can we close issue?

**Comment by vankop** [comment]
I have tested with locally, works fine with `esModuleInterop` option. As I understand it is required since there is no `default` export

**Comment by vankop** [comment]
@evilebottnawi could you publish? I will make issue in `ts-loader` later as well.

**Comment by evilebottnawi** [comment]
@vankop i am working on other feature, release will be today again :smile:
