### ISSUE TITLE
definitions tests

### ISSUE THREAD

**Issue by vankop** [webpack/schema-utils#54]
### Feature Proposal

Add tests for typescript definitions

### Feature Use Case

When typescript definitions will be generated code, we could test back forward compatibility

~~Blocked by: https://github.com/webpack/schema-utils/issues/49~~

**Comment by evilebottnawi** [comment]
I think it is unnecessary now, because typescript automatically generate declarations, and if something wrong we should report this to typescript repo

**Comment by vankop** [comment]
Actually I was thinking on this problem and still did not realized where tests for types could be useful. Since we can just realize problem in same way as we check snapshot updates. If something updated => it could be bug in code (since definitions changes) or it done by design

Will be great, if you find some explanations for this tests =)

**Comment by evilebottnawi** [comment]
I think these tests was useful when we don't auto generate declarations because we can change something in code and forget about types, but now it doesn't have sense. 

Now `invalid type` === `bug` and we should fix it and do patch release, so i think we can close this.
