### ISSUE TITLE
minLength maxLength wrong format string

### ISSUE THREAD

**Issue by vankop** [webpack/schema-utils#65]
- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- schema-utils Version:

### Expected Behavior

For
```
{
      "format": "[0-9]*",
      "minLength": 10
}
```
Expect:
`should be longer than 9 characters`

### Actual Behavior

`should be shorter than 10 characters`

### Code

https://github.com/webpack/schema-utils/blob/master/src/ValidationError.js#L412

Same for `maxLength`

**Comment by evilebottnawi** [comment]
Let's fix it :+1:

**Comment by evilebottnawi** [comment]
Done
