### ISSUE TITLE
Add declarations to git

### ISSUE THREAD

**Issue by vankop** [webpack/schema-utils#74]
### Expected Behavior / Situation

dist folder presented in git, so we can see changes in types on each PR

### Actual Behavior / Situation

dist folder is not presented in git

### Modification Proposal

I suggest to follow same approach as core repo, I agree with @sokra idea https://github.com/webpack/webpack/pull/9939#issuecomment-551425142

So we can check declarations changes as we check snapshot changes

**Comment by evilebottnawi** [comment]
Good idea, feel free to send a PR

**Comment by evilebottnawi** [comment]
Need setup CI linting for types
