### ISSUE TITLE
Bug with declarations exports

### ISSUE THREAD

**Issue by vankop** [webpack/schema-utils#75]
- Node Version: 10
- schema-utils Version: master

### Expected Behavior / Situation

expect correct export 

### Actual Behavior / Situation

Incorrect 
<img width="767" alt="Снимок экрана 2019-11-08 в 16 54 39" src="https://user-images.githubusercontent.com/10380560/68481527-81fd8d80-0248-11ea-80b8-536be2baac53.png">

### Modification Proposal

`export default function validate()` instead of `function validate(); export default validate`

<img width="548" alt="Снимок экрана 2019-11-08 в 16 56 23" src="https://user-images.githubusercontent.com/10380560/68481609-b7a27680-0248-11ea-8a39-03eba6cd8394.png">

**Comment by vankop** [comment]
Strange thing is `ValidationError` does not have export in this file at all =(

**Comment by evilebottnawi** [comment]
I tested latest PRs with types with webpack and all was fine, strange

**Comment by vankop** [comment]
Maybe ts when imports files skip errors in namespaces.. As you can see `_default` is undefined + as I said `ValidationError` does not have export here https://github.com/webpack/schema-utils/pull/76/files#diff-854a1405659189385e9df4108aea99b0R26

**Comment by evilebottnawi** [comment]
Maybe ts error?

**Comment by vankop** [comment]
🤷‍♂️
`npm run build:types` return 0 as a result

**Comment by evilebottnawi** [comment]
Thanks for create issue in ts repo

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/schema-utils/pull/84
