### ISSUE TITLE
console highlight for npm install umatches other instances

### ISSUE THREAD

**Issue by Parikshit-Hooda** [webpack/schema-utils#90]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
currently, the 'npm install schema-utils' command in the README.md appears in blue font because of 'console' tag in the readme markdown. It doesn't match other instances of 'npm install webpack' and 'npm install webpack-cli' in the org's repos. 

### Your Proposal for Changes
I believe removing the console tag would help.

**Comment by evilebottnawi** [comment]
No need

**Comment by evilebottnawi** [comment]
console should be kept, because it is highlight for common terminals
