### ISSUE TITLE
Types of property 'type' are incompatible

### ISSUE THREAD

**Issue by simon-robertson** [webpack/schema-utils#99]
- Operating System: N/A
- Node Version: 12.16.0
- NPM Version: 6.14.2
- webpack Version: N/A
- schema-utils Version: 2.6.6

### Expected Behavior

Expected property type `'string'` to be valid.

### Actual Behavior

Property type `'string'` is not valid according to TSC.

### Code

```ts
import validate from 'schema-utils'

const schema = { // using "const schema: any =" bypasses the problem
    type: 'object', // this is fine
    properties: {
        output: {
            type: 'string' // this gets flagged as an error
        }
    }
}

validate(schema, configFromSomewhere)
```

I guess this error could be occurring due to the allowed property `type` values coming from a TS enum behind the scenes, but there appears to be no access to that enum from the `schema-utils` package. There also appears to be no way to properly declare the `schema` type.

### TypeScript Error Message

```
Argument of type '{ type: string; properties: { output: { type: string; }; }; }' is not
assignable to parameter of type 'JSONSchema4 | JSONSchema6 | JSONSchema7'

Type '{ type: string; properties: { output: { type: string; }; }; }' is not assignable to
type 'JSONSchema7'

Types of property 'type' are incompatible.

Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" |
    "integer" | "array" | "null" | JSONSchema7TypeName[] | undefined'
```

### How Do We Reproduce?

Set a schema property type to `'string'` in a TypeScript project.

**Comment by Yankovsky** [comment]
@simon-robertson hey! You should either give type to schema during initialization `const schema: JSONSchema7 = {...`, or you can use `as const` assertion 
```
const schema = {
  type: 'object' as const,
  properties: {
    output: {
      type: 'string' as const
    }
  }
}
```

**Comment by Yankovsky** [comment]
That's because TS thinks that your type is more general, that it could have any arbitrary string in type property.

**Comment by evilebottnawi** [comment]
@Yankovsky Thanks!

@simon-robertson Answer above
